# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build-windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    - name: restore
      run: dotnet restore
    - name: Build Single-File Release
      run: MSBuild.exe .\Trashman\trashman.csproj @build\win-x64-singlefile.rsp
    - name: Build Single-File Self-Contained
      run: MSBuild.exe .\Trashman\trashman.csproj @build\win-x64-singlefile-selfcontained.rsp
    - name: Upload win-x64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: trashman-win-x64.exe
        path: .\out\net8.0\win-x64\publish\trashman.exe
    - name: Upload win-x64-selfcontained artifact
      uses: actions/upload-artifact@v4
      with:
        name: trashman-win-x64-selfcontained.exe
        path: .\out\net8.0\win-x64-selfcontained\publish\trashman.exe
